services:
  db:
    image: postgres:alpine3.18
    container_name: db
    environment:
      - POSTGRES_DB=jota_news
      - POSTGRES_USER=jota_user
      - POSTGRES_PASSWORD=jota_password
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jota_user -d jota_news"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=jota_user
      - RABBITMQ_DEFAULT_PASS=jota_password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: .docker/Dockerfile.api
    container_name: api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env.local

  proccess:
    build:
      context: .
      dockerfile: .docker/Dockerfile.receiver
    command: python message_queue/consumers/proccess_receiver.py
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env.local

  classifier:
    build:
      context: .
      dockerfile: .docker/Dockerfile.classifier
    command: python message_queue/consumers/classifier__source.py
    restart: always
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env.local
volumes:
  postgres_data:
  rabbitmq_data: