# Dockerfile para projeto Django 5 com python 3.12
FROM:  python:3.12-slim

WORKDIR /api

COPY ../src/server-api/requirements.txt /api/requirements.txt

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

COPY ../src/server-api /api

CMD ["gunicon", "server-api.wsgi:application", "--bind", "5000"]