# Generated by Django 5.1.7 on 2025-03-24 19:42

import django.db.models.deletion
import django.utils.timezone
import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('category'), models.Model),
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('raw_data', models.JSONField(verbose_name='Dados brutos')),
                ('clean_data', models.JSONField(blank=True, null=True, verbose_name='Dados limpos')),
                ('proccessed_data', models.JSONField(blank=True, null=True, verbose_name='Data de Processamento')),
                ('is_proccessed', models.BooleanField(default=False, verbose_name='Processado')),
                ('name_source', models.CharField(max_length=255, verbose_name='Nome da Fonte')),
            ],
            options={
                'verbose_name': 'Fonte',
                'verbose_name_plural': 'Fontes',
                'ordering': ['proccessed_data'],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('source'), models.Model),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('tag'), models.Model),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='news_app.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Subcategoria',
                'verbose_name_plural': 'Subcategorias',
                'ordering': ['category__name', 'name'],
                'unique_together': {('slug', 'category')},
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('subcategory'), models.Model),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publicado em')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Urgente')),
                ('is_classified', models.BooleanField(default=False, verbose_name='Classificado')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='news', to='news_app.category', verbose_name='Categoria')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='news', to='news_app.source', verbose_name='Fonte')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='news', to='news_app.subcategory', verbose_name='Subcategoria')),
                ('tags', models.ManyToManyField(blank=True, related_name='news', to='news_app.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-is_urgent', '-published_at'],
                'indexes': [models.Index(fields=['published_at'], name='news_app_ne_publish_254a67_idx'), models.Index(fields=['is_urgent'], name='news_app_ne_is_urge_ccd6a0_idx'), models.Index(fields=['is_classified'], name='news_app_ne_is_clas_5e147e_idx')],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('news'), models.Model),
        ),
    ]
