# Generated by Django 5.1.7 on 2025-03-25 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['processed_data'], 'verbose_name': 'Fonte', 'verbose_name_plural': 'Fontes'},
        ),
        migrations.RenameField(
            model_name='source',
            old_name='is_proccessed',
            new_name='is_processed',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='proccessed_data',
            new_name='processed_data',
        ),
    ]
