# Generated by Django 5.1.7 on 2025-03-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['proccessed_data'], 'verbose_name': 'Fonte', 'verbose_name_plural': 'Fontes'},
        ),
        migrations.RemoveField(
            model_name='source',
            name='classification_data',
        ),
        migrations.AddField(
            model_name='source',
            name='proccessed_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Data de Processamento'),
        ),
    ]
