@url=localhost:8000
#User
GET http://{{url}}/users/ HTTP/1.1

###

GET http://{{url}}/api/news/ HTTP/1.1

###
POST http://{{url}}/login/ HTTP/1.1
Content-Type: application/json

{
    "username": "edson.filho",
    "password": "mudar1234"
}

###