# Generated by Django 5.1 on 2025-03-22 17:07

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaModel',
            fields=[
                ('UUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('UUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fonte', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fonte')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('data_publicacao', models.DateTimeField(verbose_name='Data de Publicação')),
                ('autor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Autor')),
                ('categoria_original', models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoria Original')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None, verbose_name='Tags')),
                ('informacoes_adicionais', models.JSONField(blank=True, null=True, verbose_name='Informações Adicionais')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='SubCategoriaModel',
            fields=[
                ('UUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_app.categoriamodel', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'SubCategoria',
                'verbose_name_plural': 'SubCategorias',
                'ordering': ['nome'],
            },
        ),
    ]
