# Generated by Django 5.1 on 2025-03-22 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsmodel',
            old_name='categoria_original',
            new_name='categoria',
        ),
        migrations.RemoveField(
            model_name='newsmodel',
            name='informacoes_adicionais',
        ),
    ]
