services:
# Postgres - System Database 
  postgres-server:
    image: postgres:alpine3.18
    container_name: postgres-server
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dbnewsjota
      - POSTGRES_PASSWORD=newsjota
    ports:
      - 5432:5432
    networks:
      - server-hosts
      
# Django - System Admin / API REST 
  server-api:
    build:
      context: ../django_app/
      dockerfile: Dockerfile
    container_name: news-api
    #command: sh entrypoint.sh
    command: ['python', 'manage.py', 'runserver', '0.0.0.0:5005']
    volumes:
      - ../django_app/:/api
    depends_on:
      - postgres-server
      - broker-server
    restart: always
    ports:
      - "8000:5005"
    networks:
      - server-hosts


networks:
  server-hosts:
    driver: bridge