service:

# RabbitMQ - Broker
  broker-server:
    image: rabbitmq:3-management
    container_name: queue-server
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=jnews
      - RABBITMQ_DEFAULT_PASS=ep4X1!br
    ports:
      - "5672:5672"
      - "15672:15672"
      - "25676:25676"
    networks:
      - server-hosts

# Postgres - System Database 
  postgres-server:
    image: postgres:alpine3.18
    container_name: postgres-server
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=test123
    ports:
      - 5432:5432
    networks:
      - server-hosts
      
# Django - System Admin / API REST 
  server-api:
    build:
      context: ../src/
      dockerfile: Dockerfile
    container_name: secedu-api
    image: secedu-admin-web-api
    command: gunicorn --workers=2 --timeout=3600 --bind=0.0.0.0:5005 core.wsgi:application
    depends_on:
      - postgres-server
    restart: always
    ports:
      - "5005:5005"
    networks:
      - server-hosts
      - web_network