services:
  broker-server:
    image: rabbitmq:3-management
    container_name: broker-server
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=j_news
      - RABBITMQ_DEFAULT_PASS=newsjota
      - "5672:5672"
      - "15672:15672"
      - "25676:25676"
    networks:
      - server-hosts

# Postgres - System Database 
  postgres-server:
    image: postgres:alpine3.18
    container_name: postgres-server
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dbnewsjota
      - POSTGRES_PASSWORD=newsjota
    ports:
      - 5432:5432
    networks:
      - server-hosts
      
# Django - System Admin / API REST 
  server-api:
    build:
      context: ../src/
      dockerfile: Dockerfile
    container_name: news-api
    #command: sh entrypoint.sh
    command: ['python', 'manage.py', 'runserver', '0.0.0.0:5005']
    depends_on:
      - postgres-server
    restart: always
    ports:
      - "8000:5005"
    networks:
      - server-hosts

networks:
  server-hosts:
    driver: bridge