# docker/Dockerfile.receiver
FROM python:3.11-slim

WORKDIR /app

# Instalar dependências necessárias
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Instalar dependências Python
COPY ../requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copiar o código do projeto
COPY ../ /app/

# Comando para iniciar o consumidor de recebimento
CMD ["python", "message_queue/consumers/process_receiver.py"]
