@url = http://localhost:8000/

GET  {{url}} HTTP/1.1
Content-Type: application/json

###

POST {{url}}api/news/ HTTP/1.1
content-type: application/json

{
    "username": "edson.",
    "password": "mudar1234"
}

###

curl -X POST -H "Content-Type: application/json" 
-d '{"username": "edson.filho", "password": "mudar1234"}' {{url}}api/get-token/

###
POST {{url}}api/get-token/ HTTP/1.1
Content-Type: application/json

{
    "username": "edson.filho",
    "password": "mudar1234"
}